apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: liquibase-tag-exists
spec:
  params:
    - name: jdbc-database-secret
    - name: liquibase-tag
  results:
    - name: tag-exists-message
      description: liquibase tag-exists message
  steps:
    - name: liquibase-tag-exists
      image: liquibase:4.31
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash

        /liquibase/liquibase \
          --defaultsFile=liquibase.properties \
          --url="${JDBC_DATABASE_URL}" \
          --username="${JDBC_DATABASE_USER}" \
          --password="${JDBC_DATABASE_PASS}" \
          tag-exists --tag=$(params.liquibase-tag) 2> tag-exists.log

        cat tag-exists.log

        if [[ "$(cat tag-exists.log)" =~ "already exists in" ]]; then
          echo -n "yes" >> $(results.tag-exists-message.path)
        else
          echo -n "no" >> $(results.tag-exists-message.path)
        fi
      env:
        - name: JDBC_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-url
        - name: JDBC_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-user
        - name: JDBC_DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-pass

  workspaces:
    - name: source
