apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: liquibase-update-testing-rollback
spec:
  params:
    - name: jdbc-database-secret
    - name: root-changelog-file
  steps:
    - name: liquibase-update
      image: liquibase:4.31
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        
        /liquibase/liquibase \
        --defaultsFile=liquibase.properties \
        --changelog-file=$(params.root-changelog-file) \
        --url="${JDBC_DATABASE_URL}" \
        --username="${JDBC_DATABASE_USER}" \
        --password="${JDBC_DATABASE_PASS}" \
        update-testing-rollback
      env:
        - name: JDBC_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-url
        - name: JDBC_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-user
        - name: JDBC_DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-pass
  workspaces:
    - name: source
