apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: liquibase-snapshot
spec:
  params:
    - name: jdbc-database-secret
  steps:
    - name: liquibase-snapshot
      image: liquibase/liquibase:4.13.0
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        
        /liquibase/liquibase \
        --defaultsFile=liquibase.properties \
        --url="${JDBC_DATABASE_URL}" \
        --username="${JDBC_DATABASE_USER}" \
        --password="${JDBC_DATABASE_PASS}" \
        --output-file=snapshot.json \
        snapshot \
        --snapshotFormat=json
      env:
        - name: JDBC_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-url
        - name: JDBC_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-user
        - name: JDBC_DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: $(params.jdbc-database-secret)
              key: database-pass
  workspaces:
    - name: source
