apiVersion: v1
kind: Secret
metadata:
  name: jdbc-mysql-secret
type: Opaque
stringData:
  database-url: jdbc:mysql://<servername>:<port>/<dbname>
  database-user: <db-user>
  database-pass: <db-password>
  database-type: mysql
