apiVersion: v1
kind: Secret
metadata:
  name: jdbc-postgresql-secret
type: Opaque
stringData:
  database-url: jdbc:postgresql://<host>:<port>/<dbname>
  database-user: <db-user>
  database-pass: <db-password>
  database-type: postgresql
