apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: liquibase-pipeline-run-
spec:
  pipelineRef:
    name: liquibase-pipeline
  params:
    - name: git-url
      value: "<git-url>"
    - name: git-revision
      value: "<git-revision>"
    - name: git-ref-type
      value: "<git-ref-type>"
    - name: jdbc-database-secret
      value: "<jdbc-database-secret>"
    - name: root-changelog-file
      value: "example-changelog.sql"
    - name: environment
      value: "<environment>"
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
