---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: liquibase-pipeline-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: liquibase-pipeline-listener
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
      bindings:
        - ref: liquibase-pipeline-binding
        - ref: dev-env
      template:
        ref: liquibase-pipeline-template
