---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: liquibase-pipeline-template
spec:
  params:
    - name: git-url
      description: The git repository url
    - name: git-revision
      description: The git revision
      default: develop
    - name: git-ref-type
      description: Git reference type -> branch or tag
      default: branch
    - name: environment
      description: Environment to deploy
    - name: jdbc-database-secret
      description: Secret path for JDBC Database Config
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: liquibase-pipeline-run-
      spec:
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: git-ref-type
            value: $(tt.params.git-ref-type)
          - name: root-changelog-file
            value: "<root-changelog-file>"
          - name: environment
            value: $(tt.params.environment)
          - name: jdbc-database-secret
            value: $(tt.params.jdbc-database-secret)
        pipelineRef:
          name: liquibase-pipeline
        workspaces:
          - name: git-source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 100Mi