apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: liquibase-pipeline-binding
spec:
  params:
  - name: git-revision
    value: $(body.head_commit.id)
  - name: git-url
    value: $(body.repository.clone_url)
  - name: git-ref-type
    value: "branch"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: liquibase-pipeline-tag-binding
spec:
  params:
  - name: git-revision
    value: "tags/$(body.ref)"
  - name: git-url
    value: $(body.repository.clone_url)
  - name: tag-name
    value: $(body.ref)
  - name: git-ref-type
    value: "tag"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: prod-env
spec:
  params:
    - name: environment
      value: prod
    - name: jdbc-database-secret
      value: "<jdbc-database-secret>"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: dev-env
spec:
  params:
    - name: environment
      value: dev
    - name: jdbc-database-secret
      value: "<jdbc-database-secret>"
